/**
 * What's new (rev 193): what changed for members and coaches, newest first, in plain words. Kept here as data and reviewed like
 * code, never edited in the app. Every commit that changes what someone sees adds its entry in the same commit (the gate
 * checks, src/lib/engine/whats-new.ts); refactors, tests and internal fixes don't.
 *
 * `n` only ever grows: the next entry takes the highest `n` plus one. It is how the menu's dot knows what a member hasn't seen.
 * `version` is the commit it arrived in when known; an entry written in the same commit as its change can't name that commit,
 * so it shows the day's version instead.
 */
export type Audience = "everyone" | "coach";
export type WhatsNewEntry = { n: number; date: string; title: string; lines: string[]; audience: Audience; version?: string };

export const WHATS_NEW: WhatsNewEntry[] = [
  {
    n: 121,
    date: "2026-10-08",
    title: "Ship a ladder in one press",
    lines: [
      "On a comment ladder that clears its checklist and has its graphic, Ship does the rest: the post goes to your Facebook Page and Instagram through your GoHighLevel with the graphic attached (now, or at a time you set), the rungs go to Community Loyalty's drip naming the two posts, and the keyword goes to your bot. The card says what each step did, what is held and why, and Ship again runs only the parts that did not go.",
      "The graphic gets a public, unguessable address the moment you ship, so Instagram can fetch it; it carries nothing about you, and Revoke on the ladder page kills it. Never your personal profile or a group: those stay copy-and-paste.",
      "New ladder can make the graphic in the same go: pick the photo (or let HelixOS suggest one) and tick Make the graphic. The drip hand-off now names where the rungs land (the Page, Instagram or both), the Planner's post ids, the gap and whether the last rung is pinned.",
    ],
    audience: "everyone",
  },
  {
    n: 120,
    date: "2026-10-08",
    title: "Keywords that know what they fetch",
    lines: [
      "Each keyword on your ladder facts now has a target: the product (price and entry terms in the final rung, as before), one of your lead magnets (named once in the final rung, no price), or a conversation, with one line you write (no price, no product name). The final rung is written from that target, and the checklist refuses a final rung that pitches the product under a magnet or conversation keyword. A keyword with no target cannot carry a ladder to ready.",
      "A keyword also says where your bot listens for it (a comment, a DM, or both) and what it tags the person with.",
      "Your bot: the ladder facts page shows what your Community Loyalty bot holds for keywords against what HelixOS would send, and Push keywords to your bot writes the two router fields by name and reads them back. Nothing is deleted on the bot, and nothing posts or comments as you.",
    ],
    audience: "everyone",
  },
  {
    n: 119,
    date: "2026-10-08",
    title: "Make the graphic: your headline on your photo",
    lines: [
      "On a comment ladder, Make the graphic draws the headline on one of your own photos in the ladder template: the photo over the top, the fade, the two big lines with the one gold phrase, (READ COMMENTS) and your badge: avatar, name, verified tick and @handle from your Brand kit. HelixOS suggests the photo whose caption matches the headline; pick another, or upload one there.",
      "One file is kept, the sharp 2× master (2160 by 2700, PNG), in your Images as a graphic. Download it at 2× or at 1080 by 1350; Remake with another photo or an alternate headline, or a stronger fade for a busy picture. Send to composer carries it, with Download image beside the copy-and-paste versions; Instagram with no picture is refused before scheduling, not at publish time.",
      "Allow AI backgrounds, on in your Brand kit and switchable per graphic: when no photo of yours fits, a background scene can be made with your own OpenAI key. Backgrounds only; a person in a graphic is always your own real photo. Your Claude can ask for it too: ladder_make_graphic.",
    ],
    audience: "everyone",
  },
  {
    n: 118,
    date: "2026-10-08",
    title: "KPIs on your Business goals",
    lines: [
      "Any goal or key result can carry KPIs: a name, a target and a period (this week, month, quarter, year, or your own dates). Each one shows its actual against the target, a pace word (ahead, on pace, behind, done) worked out from how much of the period has gone, and a weekly chart against the straight line to the target.",
      "Three places a KPI's number can come from: read from your Numbers (calls booked, cash collected, posts and the rest, summed from your evening closes, nothing typed twice), typed in by you, or asked for in the evening close as its own box.",
      "A key result with KPIs reads on track by their pace in the tree and on your coach's line. Your Primary business goal has its first KPI already (Cash collected for a $ goal), and Today's progress bar reads it; Settings → Your one goal still sets its target.",
    ],
    audience: "everyone",
  },
  {
    n: 117,
    date: "2026-10-08",
    title: "Business goals: one linked plan",
    lines: [
      "Business goals, under Grow: your goals, the key results that prove them, the initiatives that move them, and the tasks that do the work, linked both ways. A tree view, and a table you can filter by kind, status, owner, due date and pathway stage.",
      "Your one goal from Today is now your Primary business goal, marked ★; nothing you set is lost. Open any record to edit it, link it up or down, archive it, or add and tick its tasks.",
      "Your coach sees a read-only line on your client page: goals, key results on track, initiatives not started. KPIs with pace and charts come next.",
    ],
    audience: "everyone",
  },
  {
    n: 116,
    date: "2026-10-08",
    title: "One phrase in your accent, and a layout menu per slide",
    lines: [
      "Each headline can carry one phrase in your kit's accent: the deck suggests it (a figure, or the words after a colon) and on the Deck step you tap words to change it or clear it. Where the accent would not read on that slide's ground, the phrase is bold ink instead, and the kit check says so.",
      "Every slide on the Deck step has a Layout menu: Auto names the deck's own pick, and you can set the layouts that slide can take (headline and body, one line centred, big number, cards, From → To). Your choices stay with the slide while you edit elsewhere.",
      "Logos: the cover logo sits left with the title in a taller box; the footer logo is a third of an inch. The check before download measures the text once your faces have loaded. The kit card says when you have a logo in Images that is not picked yet.",
    ],
    audience: "everyone",
  },
  {
    n: 115,
    date: "2026-10-08",
    title: "Your Proof Bank from Airtable",
    lines: [
      "Coaches: Import from Airtable on the Proof Bank brings your Testimonials table in, each clip as an approved proof with who said it (first name and last initial), the call, the time and the Fathom link, and its categories as tags. Nothing goes on your bot until you put it there.",
      "Filter the bank by tag; Results & Revenue, Sales Wins and Transformation come first. Run it again any time: what is already here is skipped.",
    ],
    audience: "coach",
  },
  {
    n: 114,
    date: "2026-10-08",
    title: "Platforms, renamed",
    lines: ["In the Platforms section of the menu, Community Loyalty now shows a 🤖 and the app is called the Omnichannel Marketing System, with a 💸."],
    audience: "everyone",
  },
  {
    n: 113,
    date: "2026-10-08",
    title: "Thirty small frictions, gone",
    lines: [
      "Settings is in the menu; gold buttons have dark text; the price box on an offer is wide enough to read; Proof Bank rows and the Settings forms fit a phone; task buttons say Top 3, Tomorrow and Delete on a desktop too; Images loads thumbnails as you scroll and has search, a kind filter and pages.",
      "A post that didn't send stands in a red banner on the post, on the board and on Today, with a Fix it button that goes where the fix is. The composer takes a photo (camera or upload) or a pick from Images. The content calendar pages back and forward. Office Hours shows the call's time and the link to join.",
      "The webinar list and the webinar page count the same checks; the step strip shows the method's stage numbers; the close-the-day and 30-day build cards sit where they should on Today; empty lessons are hidden until your coach fills them; every detail page has its own tab title.",
    ],
    audience: "everyone",
  },
  {
    n: 112,
    date: "2026-10-07",
    title: "Platforms in the menu, and a deck that lays out cleanly",
    lines: [
      "A Platforms section at the bottom of the menu (and on Everything on your phone) opens Community Loyalty, the Academy and the Evolve Omega App in a new tab.",
      "Your deck: the From → To dividers, the offer table and the guarantee no longer print on top of each other, no slide carries an empty \"Click to add text\" box, and the Deck step checks for boxes that overlap as well as text past its box. A Proof Block with no proof yet is one red slide saying what to add, and [PROOF PLACEHOLDER] never lands on a slide or a recap.",
      "A one-item offer table sits in the body with the item large; the offer section's own points come before the table; the close stands large and centred; the deck uses only the logo your Brand Kit names; wide faces such as Montserrat step down sooner; and \"Make slides for every section\" on the Deck step does every section with a script but no slides in one go.",
    ],
    audience: "everyone",
  },
  {
    n: 111,
    date: "2026-10-07",
    title: "Choosing a file: real buttons, and the camera apart from the library",
    lines: [
      "Wherever you add a file (a lead magnet, a RENPHO export, a proof, deck images, a screenshot on an issue report, an FAQ import, a meal photo in HumanOS) the plain browser box is gone. For a picture you get \"📷 Take photo\" and \"🖼️ Upload photo\" as two buttons, full width on a phone; for anything else, one \"Upload file\" button.",
      "What you chose shows beneath as a thumbnail or its name, with a ✕ to clear it before you send.",
    ],
    audience: "everyone",
  },
  {
    n: 109,
    date: "2026-10-07",
    title: "Composer: a reconnected Instagram still posts, and \"Schedule\" says when it saved nothing",
    lines: [
      "If you reconnect Instagram (or any account) in GoHighLevel, HelixOS finds the same account again before it posts and heals the channel map on its own; a refused post now says which account id was sent.",
      "Pressing Schedule when every channel was already posted now says so by name (\"Nothing scheduled: Facebook business page already posted\") and leaves the post's status as it was, instead of \"Saved 0 versions\" and \"Scheduled\".",
      "On the Distribute page, a published channel has \"Post again to this channel\" for a deliberate second post.",
    ],
    audience: "everyone",
  },
  {
    n: 107,
    date: "2026-10-07",
    title: "Team access: invite a VA or team member",
    lines: [
      "Settings now has a Team card. \"Invite team member\" makes a link that works once, for 7 days; whoever opens it creates their own login and lands in your HelixOS as a team member, up to 5 of them (your coach can change that).",
      "A team member works in your content, DMs, tasks, webinars and contacts, and nothing else: not your day, your HumanOS, your connections, your billing or your team. Every change they make is listed under Team as theirs, with who added them and when they were last active. Remove someone and their access ends on their next request.",
      "If you're part of more than one HelixOS (your own and a team you're on, or two workspaces), you pick which one after signing in and switch from the sidebar.",
    ],
    audience: "everyone",
  },
  {
    n: 106,
    date: "2026-10-06",
    title: "Your own Brand Kit",
    lines: [
      "Settings now has a Brand Kit card for you: your colours, fonts and logo. Your decks render in your own kit, never anyone else's, and until you save one they use the house starter kit.",
      "Today nudges you to set it (about 5 minutes), and your coach can set it up with you when \"Let my coach work\" is on.",
    ],
    audience: "everyone",
  },
  {
    n: 105,
    date: "2026-10-06",
    title: "Your deck: speaker notes you can talk from",
    lines: [
      "Each slide's speaker notes now start with what to say, taken from that section's script, and how long the slide gets, with how far into the webinar you'll be at its end. The Deck step shows the same under each slide.",
      "Before you download, the Deck step lists any figure you've written two ways, such as \"$5,043 week\" on one slide and \"$5,000 week\" in a script, so you can pick the right one.",
    ],
    audience: "everyone",
  },
  {
    n: 104,
    date: "2026-10-06",
    title: "Your deck: the offer builds as a table",
    lines: [
      "Each part of your offer adds its row to one table, with a check, its name and its value, so the room watches the stack grow; each bonus gets its own slide with its value large.",
      "Then one slide lists everything with the total value struck through and an arrow to your price, and your guarantee gets its own slide beside a seal.",
    ],
    audience: "everyone",
  },
  {
    n: 103,
    date: "2026-10-06",
    title: "Your deck: big numbers, cards, and From → To",
    lines: [
      "A key point with a number in it (\"602 comments on my post in 48 hours\") now shows the number huge with the words under it; two or three numbers in one line sit side by side.",
      "Your outcomes and \"This is for you if…\" are now cards side by side instead of a bulleted list, and each belief divider shows the old belief small, then the new one large.",
    ],
    audience: "everyone",
  },
  {
    n: 102,
    date: "2026-10-06",
    title: "HumanOS: Health goals that tell you if you're on pace",
    lines: [
      "HumanOS has a Health goals page now, and you can have several at once: a number on the scale, your waist, a lift (say 225 lb for 5), a habit or workouts so many days a week, or average sleep. Your weight goals carry over.",
      "Each goal runs from where you started to your target on the 7-day average. It shows the pace a week it needs, the pace you've kept over the last three weeks, whether you're on track, a little behind or behind, and when you'll land at this rate. If a date asks for more than about 1% of bodyweight a week, or half a point of body fat, it says that's an aggressive pace and suggests a gentler date.",
      "The two that need you most show on Today. They're also in the week's rollup and in the end-of-day read's line for tomorrow when one is behind, and your coach sees them if you share HumanOS. Your own Claude can read and set them too.",
    ],
    audience: "everyone",
  },
  {
    n: 101,
    date: "2026-10-06",
    title: "Your deck says each thing once",
    lines: [
      "A key point that repeats your opening (the chat prompt, the promise, an outcome) or a beat of your origin story is now one slide, not two. The Deck step lists each one it left out and what it repeats, so you can change it if you meant something new.",
      "A testimonial that starts mid-sentence (\"ran a five-day challenge…\") now reads with the person's first name in front (\"Terri ran a five-day challenge…\").",
    ],
    audience: "everyone",
  },
  {
    n: 100,
    date: "2026-10-06",
    title: "Today: the lock-in up top, and your tasks in full",
    lines: [
      "Before you lock in, the morning lock-in is the big card at the top of Today, at full width, instead of a slim card lower down.",
      "Pick your top 3 is one list with each task's whole title, its late tag and its due date, and a count of how many you've picked. The energy buttons each fit their label.",
      "Once you're locked in, it folds into a short summary (your energy, your win line, your three picks to tick off, and Edit), with the 30-day build right under it.",
    ],
    audience: "everyone",
  },
  {
    n: 98,
    date: "2026-10-05",
    title: "HumanOS: weigh-ins from Apple Health",
    lines: [
      "Your morning weigh-in can now arrive on its own. In HumanOS settings, under Devices, Connect Apple Health makes a key for a Shortcut on your iPhone that runs each morning with no tap and sends your weight, body fat %, lean body mass and BMI from Health. The steps to set it up are right there.",
      "The key is shown once. Revoke stops it at once, and Make a new key replaces it. The same weigh-in sent twice, or one you already typed or brought in from the RENPHO export, stays one row on Weigh-ins. RENPHO's other numbers (visceral fat, water, bone and the rest) stay in RENPHO, so its export is still the way to bring those in.",
    ],
    audience: "everyone",
  },
  {
    n: 97,
    date: "2026-10-05",
    title: "Avatars: the buyers you serve, matched to your offers",
    lines: [
      "Avatars, under Build next to Offers, keeps several buyer avatars in one place, with sub-segments under each. For each one you can write who they are, their pains, what they want, what they've tried, their objections, where they hang out, the words they use, why now, how your framework helps and who it's not for. Star one as your Primary.",
      "Link each avatar to the offers they'd buy. On an offer, \"Who it's for\" shows its avatars with one as the main, and says so gently when none is linked. The first time you open Avatars, each offer's \"one person this is for\" comes in as an avatar marked \"imported, please review\".",
      "Drafts write to the right buyer. Webinar sections, lead magnets, ladders and the composer's polish use the offer's main avatar (else your Primary) in your own words and add nothing to them. A webinar's \"Who it is for\" slides use the avatar when the offer's own lines are empty. Day 1 of the 30-day build saves straight into your Primary, and your own Claude can list, add and update avatars and link them to offers.",
    ],
    audience: "everyone",
  },
  {
    n: 96,
    date: "2026-10-05",
    title: "HumanOS: one pattern in your day's read",
    lines: [
      "Once you have three weeks of days to compare, the end-of-day read in Close the day can add one sentence about a pattern in your numbers. For example: \"More sleep tends to go with more calls booked the next day (r 0.52 over 34 days).\"",
      "It covers sleep, strain and recovery, food, habits and your business numbers, a different pairing each day. It only speaks up when the link is clear and held over time, and it says \"tends to go with\", never that one causes the other.",
    ],
    audience: "everyone",
  },
  {
    n: 95,
    date: "2026-10-05",
    title: "HumanOS: merge duplicate exercises",
    lines: [
      "If the same exercise shows up twice, say \"Leg Curl\" from an import beside \"Seated Leg Curl\", open Edit on the one to let go and choose Merge into…. A preview first says what moves (\"Move 9 sets (Mar 21 to Apr 12) into Seated Leg Curl; PR becomes 105 × 10\").",
      "Merge moves every set with its date onto the exercise you keep, and your routines follow. The merged one is archived, not deleted, and Undo stays open for 7 days. Your own Claude can do it too, and asks before it merges.",
    ],
    audience: "everyone",
  },
  {
    n: 94,
    date: "2026-10-05",
    title: "Your deck: easier to read, a real price slide, and a close",
    lines: [
      "Slide text is bigger: body lines are 24pt where the slide has room, and the red \"add a picture\" boxes read at 20pt. The cover has more air between your title and your name, and shows your webinar's date and time when you've set one.",
      "The price slide now says \"Get started today\" with the price large, your total value struck through and \"You save…\" beneath it. Each stack slide shows that item's own value large, with the running total small under it.",
      "Your call to action shows only on the offer and Q&A slides, once (the CTA bar replaces the footer line, never both), and every deck ends on your call to action and a Q&A slide that keeps it on screen. The Deck step's previews now use your kit's Google fonts, so they match the file you download.",
    ],
    audience: "everyone",
  },
  {
    n: 93,
    date: "2026-10-05",
    title: "Your first deck: a starter kit, and a logo that shows",
    lines: [
      "With no brand kit of your own yet, your deck uses a house starter kit (warm off-white, deep slate, teal, Montserrat headings) instead of plain grey. Settings shows it filled in, ready to change, and Reset to the starter kit takes you back to it.",
      "Your logo is bigger on the cover. A dark logo that would vanish on the dark cover now sits on a small light badge, or add a \"Logo for dark backgrounds\" to your kit and it goes there instead. With no logo at all, the cover shows a red \"Your logo here\" box, so you can see what to add.",
      "With a logo in the footer bar, the footer no longer also spells out your brand name beside it. A webinar drafted with ✨ before it has any proof now exports: the proof slides wait for your proof instead of blocking the download.",
    ],
    audience: "everyone",
  },
  {
    n: 87,
    date: "2026-10-05",
    title: "Recordings: what's new, what's yours, and the moment it was said",
    lines: [
      "Recordings lists your coaching calls newest first, by week, with a yellow dot on each one you haven't opened yet and the count on the menu. Mark all as seen clears them.",
      "On a call, the action items sit under the person each is for, yours first, and each one's ▶ time opens Fathom at that moment. Today's Then panel names the calls that still have an item for you.",
      "Coaches: Published shows \"Seen by N of M\" for each call, and a new Action items tab lists your last two weeks' items by person, drafts included.",
    ],
    audience: "everyone",
  },
  {
    n: 86,
    date: "2026-10-05",
    title: "The Monday post: the right thread link, and @everyone where you wrote it",
    lines: [
      "The weekly post's link now always opens the post itself in the community. HelixOS waits for the community's own post id before it makes the link, so \"copy and open this week's thread\" never lands on \"Post not available\".",
      "@everyone stays in your sentence, where you wrote it (\"Share below @everyone so…\"). Notify all members is what reaches everyone, as before.",
      "Coach → Community warns \"No graphic set: the post goes out without an image\" when the Monday or month post is on with no graphic chosen.",
    ],
    audience: "coach",
  },
  {
    n: 85,
    date: "2026-10-05",
    title: "Webinars: drafting a section writes its slides too",
    lines: [
      "✨ Draft this section for me now writes the slides as well as the script: one short line per slide in Key points, so a webinar you draft from scratch exports with slides in every act. Key points you already typed are never overwritten.",
      "A section with a script and no key points gets a Make slides from my script button, and the Deck step lists every such section so none is skipped. A slide line never quotes a number your webinar doesn't have, and a missing proof stays a red placeholder.",
      "The offer section's draft now uses your linked offer's own stack and price. A draft that comes back cut off is no longer saved, and \"2 a.m.\" no longer turns into \"2 m.\"",
    ],
    audience: "everyone",
  },
  {
    n: 84,
    date: "2026-10-05",
    title: "Recordings: your publishing rules and a list you can scan",
    lines: [
      "Coach → Recordings → Publishing rules: a call whose Fathom title names one of your series (Automation Accelerator, Community Building, Business Strategy, Open Office Hours) publishes itself to that program. A call with no useful title goes by the time it started (Los Angeles time, within 15 minutes) and gets a clear name like \"Evolve Omega Accelerator · Mon 9 AM\", with Fathom's title under it. Edit both lists there.",
      "To review shows one short row per call, grouped by series and time slot with a count, with filters. Calls with only you on them wait folded under \"Just you\", and never publish themselves. Review opens one call: the summary, who was on it (no email addresses), and Publish as suggested.",
      "Calls already here follow the same rules as suggestions: tick several to publish them all as suggested, or Skip them (kept under Skipped, never deleted from Fathom).",
    ],
    audience: "coach",
  },
  {
    n: 83,
    date: "2026-10-05",
    title: "HumanOS: held means held, and next time's weights fit your machines",
    lines: [
      "The workout read judges each exercise by its top set: heavier, or more reps at the same weight, is up; the same top set is held; lighter or fewer reps is down. A fade or less volume gets its own line instead of counting as down.",
      "Next time's weight goes up one step that fits the machine. HumanOS learns the step from the weights you've logged on it, or from the number you type when you change a suggestion. You can also set it under Steps up by on the exercise.",
      "Use next time now opens the weight so you can type what you'll actually load, on Training, on Today, or by telling your Claude. Next session, the read shows what you planned beside what you did.",
    ],
    audience: "everyone",
  },
  {
    n: 81,
    date: "2026-10-04",
    title: "Your drafts follow you to your other devices",
    lines: [
      "Start your month's answers on your laptop and finish them on your phone: anything you've typed but not saved yet comes back on whichever device you open the form on, with \"Draft restored\".",
      "A draft goes away once you save, and after 30 days untouched. It's yours alone: your coach never sees it, and it isn't kept while your coach is working in your HelixOS.",
    ],
    audience: "everyone",
  },
  {
    n: 80,
    date: "2026-10-04",
    title: "HumanOS: your body's day, in Close the day",
    lines: [
      "From the evening on, Close the day on Today carries a short read of your body's day next to your business numbers. It covers the workout in a line, food against your day type's targets (protein first, and what's still to go if it's early), sleep, recovery and strain, the habits you kept, and your weight trend by its 7-day average rather than one weigh-in.",
      "It ends with one thing to change tomorrow. Your own Claude can read it to you too. It's private: only you see it.",
    ],
    audience: "everyone",
  },
  {
    n: 79,
    date: "2026-10-04",
    title: "HumanOS: every scale number, one reading per weigh-in",
    lines: [
      "Weigh-ins is in the HumanOS menu. Tap Every number under a reading to see all it holds: body fat, fat-free and fat mass, muscle, bone mass, water, protein, subcutaneous and visceral fat, BMR, metabolic age and BMI.",
      "Logging through your Claude now saves every number a RENPHO screenshot or export shows, and marks it as from RENPHO.",
      "A weigh-in logged twice, say typed in the morning and then imported from RENPHO, stays one reading. The second fills in the numbers the first didn't have, and changes nothing that's already there.",
    ],
    audience: "everyone",
  },  {
    n: 78,
    date: "2026-10-04",
    title: "HumanOS: how the workout went, and next time's weight",
    lines: [
      "When you finish a workout, Training reads it back in a few lines: sets done against the plan, time and strain from WHOOP, each exercise up, held or down against last time, new PRs, reps that faded, and anything that hasn't moved for a while. Your note is part of it. Today shows the same lines.",
      "Where you earned it, it suggests next time's weight: the smallest step up when every set hit the top of your reps, or the same weight again when they faded. Use next time makes it the routine's target, and your first set opens on it.",
      "Stretching or sauna that WHOOP recorded within an hour of the lift is grouped with it as one gym visit, with the total time. A habit whose name holds the activity, like \"Sauna session\", now gets ticked too.",
    ],
    audience: "everyone",
  },
  {
    n: 76,
    date: "2026-10-04",
    title: "HumanOS: WHOOP keeps up, and Sync now says what it did",
    lines: [
      "Sync now on HumanOS settings is quicker: it picks up from your last sync instead of pulling a whole month. When it's done it tells you what came in (\"Synced: 2 new workouts\"), or why it couldn't.",
      "WHOOP is now checked every hour as well, so a workout WHOOP didn't tell us about straight away still shows up within the hour.",
      "If a sync stops part way, HumanOS settings says so, and why.",
    ],
    audience: "everyone",
  },
  {
    n: 75,
    date: "2026-10-04",
    title: "Money the way you write it, and nothing typed is lost",
    lines: [
      "Every money box takes amounts the way you'd write them: \"3.5k\", \"$3,500\", \"3500 USD\", \"1.2m\". Under the box it says what it understood (\"Reads as $3,500\") before you save, and one it can't read is never saved as 0.",
      "If a form refuses something, everything you typed stays and only the box to fix is marked. Your week's 3-1-3, Close the day, the webinar steps and your Pathway submissions now keep a draft too, like the month's answers already did.",
    ],
    audience: "everyone",
  },
  {
    n: 74,
    date: "2026-10-04",
    title: "Business name back on sign-up, and the chat bubble out of the way",
    lines: [
      "Signing up asks for your business name again, and it's required. It's the same name Settings → Business shows, so you can change it there any time.",
      "On a phone, the Ask Danno bubble now sits just above the buttons at the bottom of the screen instead of on top of them.",
    ],
    audience: "everyone",
  },
  {
    n: 73,
    date: "2026-10-03",
    title: "A simpler sign-up, and tiers that save",
    lines: [
      "Signing up now asks for your first and last name and your password twice, with Show passwords to check them; if something is refused, everything you typed stays in the form. Your business name is added later on Settings.",
      "For coaches: a client's tier on the Coach page saves the moment you pick it, shows in full, and no longer touches the pass. The points column is now called Level, and the pass button reads \"Pass: on\" or \"Pass: off\".",
      "Connecting GoHighLevel asks for one more permission, contacts.readonly, for the impact tracker that's coming.",
    ],
    audience: "everyone",
  },
  {
    n: 72,
    date: "2026-10-03",
    title: "Past feedback and Office Hours, brought over from Airtable",
    lines: [
      "For coaches: History from Airtable (linked from Monthly feedback) brings past monthly feedback and Office Hours requests over from the Omnichannel base. Paste a read-only token, check the dry run, then Approve.",
      "Each row lands on the member with that email, in their own words and dated when it was sent, so nothing old shows as new. A month a member already answered in HelixOS stays theirs, a second run adds nothing, and anything that can't be placed is listed with the reason.",
    ],
    audience: "coach",
  },
  {
    n: 71,
    date: "2026-10-03",
    title: "HumanOS: numbers the way you write them, and nothing typed is lost",
    lines: [
      "Every HumanOS number box reads what you'd naturally type: \"70 kg\" or \"154 lb\" for a weigh-in whichever units you use, \"500 ml\" for a water habit tracked in fl oz, \"1 lb\" of a food counted in ounces, a decimal comma (\"2,5\"), \"2.2k\" or \"30 tablets\".",
      "If something can't be read, the form says which box to fix, marks only that box, and keeps everything else you typed.",
      "Foods, meals, habits, routines, supplements & meds, day types and your HumanOS settings keep a draft as you type, so a reload or a dropped connection brings it back.",
    ],
    audience: "everyone",
  },
  {
    n: 70,
    date: "2026-10-03",
    title: "HumanOS: an easier Pantry",
    lines: [
      "Par levels now list only the foods that have one, each name on one line with its amount beside it. To give another food a par level, use Add a par level and pick it from the list.",
      "Add to the shelf gives the food its own full-width line, so long names are readable, and the unit box says what it wants in full.",
    ],
    audience: "everyone",
  },
  {
    n: 69,
    date: "2026-10-03",
    title: "Every morning starts clean",
    lines: [
      "A new day's lock-in starts fresh: yesterday's Top 3 that you didn't finish loses its star, and it's offered first in the morning's picker under \"Still open from yesterday\", unticked, so you choose again.",
      "Your Top 3 on Today is quieter: just the task, when it's due and its points, without the category.",
      "Connecting GoHighLevel asks for one more permission, locations.readonly, and the green Connected line now shows your sub-account's name, so you can see which account is connected.",
    ],
    audience: "everyone",
  },
  {
    n: 68,
    date: "2026-10-03",
    title: "Tell your coach about an issue or an idea",
    lines: [
      "\"I have an issue or a suggestion\" is now in the menu on every page (under More on a phone). Say what happened or what you'd like, pick how much it gets in your way (red blocking, orange annoying, green an idea), and add a screenshot if it helps: upload one, or capture the screen where your browser allows it. The page you were on goes with it.",
      "If an Ask Danno answer was wrong or out of date, pick that kind, paste the question and the answer, and tick if you'd like to talk about it.",
      "For coaches: everything lands in Issues and ideas, newest first, with Seen and Done; new monthly feedback now shows as a count on the Coach page, in the menu and on Today, and the feedback form tells members their coach reads every answer.",
    ],
    audience: "everyone",
  },
  {
    n: 67,
    date: "2026-10-03",
    title: "A save that doesn't go through no longer loses what you typed",
    lines: [
      "If a save fails (the connection drops, the page errors, or HelixOS updates while you're typing), your month's answers, your feedback, an Office Hours request, Essence or an offer come back the next time you open the page, with a line saying the last save didn't go through. Press Save again and you're done.",
      "When something goes wrong on a page, you now see a plain message and a Reload button, with the menu still there, instead of a blank screen.",
    ],
    audience: "everyone",
  },
  {
    n: 66,
    date: "2026-10-03",
    title: "HumanOS: supplements, vitamins and prescriptions, with refills",
    lines: [
      "Practices has a Supplements & meds page: what you take, the dose, how often and with or without food, and how many you have. It says when you'll run out, and for a prescription when the refill opens (\"12 days before you run out\", or once a share is used), how many repeats are left, and when the script expires.",
      "Take chips sit on Today like your habits, with a line when something needs doing. Refilled adds a fill, Filled pill boxes moves days of doses into your boxes, and Count what's left fixes the number.",
      "It's private like your health log: your coach sees it only if you switch that on here, and an AI reads it only with its own switch. HumanOS records what you enter; it never suggests a dose or checks interactions.",
    ],
    audience: "everyone",
  },
  {
    n: 64,
    date: "2026-10-03",
    title: "HumanOS: metric or US, and how hard a habit is",
    lines: [
      "HumanOS settings has one Measures choice, Metric (kg, g, ml, km) or US (lb, oz, fl oz, mi), first set from your time zone. Weight, food weights, water and other amount habits, and WHOOP's distances follow it, and Claude answers in it. Switching never changes anything you logged.",
      "A habit can be marked easy, medium or hard; it shows as one to three dots beside it on Practices and Today, and changes nothing about how it counts.",
    ],
    audience: "everyone",
  },
  {
    n: 63,
    date: "2026-10-03",
    title: "HumanOS: food search fills USDA's blanks, and Instacart is coming soon",
    lines: [
      "When a USDA entry has no calories, Find a food takes USDA's Atwater energy, or works it out from the protein, fat and carbs and says \"estimated from macros\". A nutrient the entry leaves blank shows as —, never 0, and saving tells you what to fill in.",
      "Instacart isn't taking new partners yet, so its button reads \"Instacart: coming soon\". Your shopping list works as before without it.",
    ],
    audience: "everyone",
  },
  {
    n: 62,
    date: "2026-10-03",
    title: "Run your day from a chat with Claude",
    lines: [
      "With HelixOS connected to Claude (Connect to Claude in the menu), you can now say what you'd tap: add a task, see what's due, tick one off, move it to tomorrow, lock in your Top 3 with your energy and the line you commit to, and close the day with your numbers and your win.",
      "It follows the same rules as the Today and Tasks pages: points score once, a redone lock-in tells you what it replaced, and a close tells you the points and the month's cash against your goal. Nothing is ever deleted from a chat.",
    ],
    audience: "everyone",
  },
  {
    n: 61,
    date: "2026-10-03",
    title: "HumanOS: set it up by talking to Claude",
    lines: [
      "With HumanOS connected to Claude, you can now add a food (per its unit, with its macros), save a meal from your foods, add a habit (any of the starters by name, or your own), add an exercise and put it on a routine, and read or change your day types (a band, or which day type a date runs as), all by voice.",
      "Anything already there is named back to you rather than doubled, a change says what it replaced, and nothing is ever deleted from Claude.",
    ],
    audience: "everyone",
  },
  {
    n: 60,
    date: "2026-10-03",
    title: "Your coaching calls, inside HelixOS",
    lines: [
      "A new Recordings page lists the calls your coach has published for you: the title, the date, the program, Watch in Fathom, the summary and the action items. It appears in your menu once the first one is published for you. Each action item has one tap, Make this my task, which puts it on today's list as your own task; nothing is added without your tap.",
      "View transcript fetches the words once from Fathom and keeps them, so everyone who can see the call reads it from HelixOS after that.",
      "For coaches: connect your own Fathom key on Integrations and register the webhook. A call titled Evolve Omega Accelerator or Evolve Omega Academy publishes itself to its program; every other call waits as a draft on Recordings, where you publish it to a program or to named members with one tap, hide a transcript, or unpublish.",
    ],
    audience: "everyone",
  },
  {
    n: 59,
    date: "2026-10-03",
    title: "Connecting GoHighLevel is one button, and nothing gets cut off",
    lines: [
      "Settings → Publishing is now one sentence and a Connect button. Connect opens five plain steps (open Private Integrations, create one named HelixOS, Copy the list of permissions, paste the token, paste the Location ID); once connected the card shows a green Connected with your pages and channels, Check again, Disconnect and Reconnect, and never shows the token or IDs again. Errors say what happened in plain words.",
      "Names and titles you pick or act on now wrap to a second line instead of ending in \"…\": conversations, the content calendar, the Essence steps, the pathway stages, the rewards log, the ladders and their rungs, the leaderboard.",
    ],
    audience: "everyone",
  },
  {
    n: 58,
    date: "2026-10-03",
    title: "The deck file is built on real layouts, in your theme",
    lines: [
      "The exported .pptx now sits on one master with a layout per slide family (cover, content, statement, each with and without a picture, and the picture-only slide), with real title and body placeholders. Your kit's colours are the file's theme colours and your faces its theme fonts, so changing the accent or a font in PowerPoint, Keynote or Google Slides changes every slide at once, no per-slide edits.",
    ],
    audience: "coach",
  },
  {
    n: 57,
    date: "2026-10-02",
    title: "A check before you download",
    lines: [
      "Above Download .pptx on the Deck step, one panel counts what to look at first: empty picture slots, slides with text past its box (measured on the thumbnails, not guessed), a missing logo, a licensed face with no fallback, and unfilled [placeholders]. Nothing here stops the download; it says what the file will carry.",
    ],
    audience: "coach",
  },
  {
    n: 56,
    date: "2026-10-02",
    title: "See the slides before you download",
    lines: [
      "The Deck step now shows every slide as the file lays it out: your colours and faces, the picture or the red placeholder in its frame, the footer band. Each box sits exactly where the export puts it.",
      "A slide with a problem is marked: an empty picture slot, text past its box (measured in your browser, not guessed), or no logo. The line above the thumbnails counts them.",
    ],
    audience: "coach",
  },
  {
    n: 55,
    date: "2026-10-02",
    title: "Pictures to gather: a shot list from day one",
    lines: [
      "The Foundation step now lists every picture the deck will ask for, grouped by kind (photos of you, screenshots of results, proof, diagrams, your logo), each naming the slide it serves, with the count: \"5 of 14 gathered\". Today carries the count as an action until it is complete, so you gather while you write, not the night before.",
      "\"I don't have this\" drops a picture: its slide exports as text with no placeholder and it leaves the count; Put back returns it. The Deck step says how many were dropped.",
    ],
    audience: "coach",
  },
  {
    n: 54,
    date: "2026-10-02",
    title: "Upload a picture right on the slide, and several at once",
    lines: [
      "On the Deck step, every empty picture slot has \"Upload a picture for this slide\": choose the file, and it fills that slot the moment it is saved, and joins your Images library for reuse. The kind starts as what the slide asks for.",
      "On Images and on a slide, choose several files at once. Each has its own kind, caption and consent; if one is not ready (a screenshot with nobody named), nothing is sent until it is.",
    ],
    audience: "coach",
  },
  {
    n: 53,
    date: "2026-10-02",
    title: "A brand kit you can fill in, with a preview",
    lines: [
      "On Settings, the brand kit's colours are pickers with the hex still there to edit; the faces come from a list (the faces most machines have, plus Google's), or \"Other (licensed font)\" typed by name with one line saying who will not see it; the logo can be uploaded right there and is picked at once.",
      "A preview of a cover, a content slide, a moment slide and the footer band draws itself from the kit as you type, and marks a slide whose text cannot read. A colour pair under the floor now proposes a colour to try, with Apply, instead of only refusing; an accent too light for small text is explained: the deck uses it for rules and buttons, never words.",
      "In the exported file, every picture's alt text is your caption, or the slot's own instruction when there is no caption.",
    ],
    audience: "coach",
  },
  {
    n: 52,
    date: "2026-10-02",
    title: "Practices: archived habits can come back, or go for good",
    lines: [
      "Under Edit on Practices, \"Archived (n)\" lists the habits you archived, with when and how many days each was logged. Restore puts one back where it was, logs and streak intact.",
      "Delete, only from that list, asks first (\"Delete \"Sauna\" and its 12 logged days?\") and then removes the habit and every log for good. Nothing active is one tap from gone.",
    ],
    audience: "everyone",
  },
  {
    n: 51,
    date: "2026-10-02",
    title: "Images: no people in this, graphics and diagrams, shown whole",
    lines: [
      "A screenshot or proof with nobody in it (a logo, a chart, a screen with no one's details) takes one tick, \"No people in this\", instead of a name. It is stored with the time, like the consent tick.",
      "Two new kinds: Graphic / social post (a designed image) and Diagram (your own framework or mechanism). Both sit whole inside their frame on a slide, never cropped, and a graphic is never suggested for a slot, only chosen. The library shows a photo cropped to its card and everything else whole.",
    ],
    audience: "coach",
  },
  {
    n: 50,
    date: "2026-10-02",
    title: "HumanOS: templates from your coach, and a weekly check-in you send in one tap",
    lines: [
      "Your coach can send you a copy of one of their own day types, saved meals or routines. It waits under \"From your coach\" on Log and on the matching page; Accept makes it yours to edit (foods and exercises you don't have yet are added by name), Not now sets it aside. Your coach sees nothing of yours either way.",
      "On This week, \"Send this week to your coach\" sends the week's numbers (days logged and in band, averages, sessions, sets, PRs, weight, sleep, habits) plus one note, whether or not your coach can see your days. Never a food, a day's note, a photo or your health log. One a week; sending again replaces it, Delete takes it back for your coach too.",
      "Coaches: \"Send a template\" and \"Check-ins\" on each client's page, and a ✉️ on the roster for a client who sent this week's.",
    ],
    audience: "everyone",
  },
  {
    n: 49,
    date: "2026-10-02",
    title: "The brand kit on the deck: logo, brand line, fonts, fit",
    lines: [
      "The brand kit takes a logo from your Images library: it sits on the cover and in the footer bar. The footer's brand line is the kit's name (or a line you set on the webinar's Foundation step), not the workspace's. The kit's fallback face is now the file's theme font, so text anyone adds in PowerPoint takes it.",
      "A one-line slide with no body is a statement: centred and large. Text beside a picture shrinks to fit its column, and when it cannot, the picture takes the next slide instead of running over the text. Footer text reads in the muted colour and its boxes no longer overlap.",
    ],
    audience: "everyone",
  },
  {
    n: 48,
    date: "2026-10-02",
    title: "WHOOP, the rest of it: workouts under your session, sleep stages, and the day's burn",
    lines: [
      "A WHOOP workout now sits under that day's Training session, with its heart-rate zones and distance; a day with no logged routine gets a session of its own, \"From WHOOP\", never twice.",
      "Sleep shows each night's bed and wake times and its stages (deep, REM, light, awake). Patterns gains them as metrics, with bedtime drift (how far a night strays from your week's usual), recovery, strain, resting heart rate, HRV, average heart rate and the day's energy estimate.",
      "Log and This week show the day's energy burned beside intake, worded as the estimate it is, and Settings shows the max heart rate your device reports.",
    ],
    audience: "everyone",
  },
  {
    n: 46,
    date: "2026-10-02",
    title: "Practices: today is an outline until it's kept, and the week is drawn whole",
    lines: [
      "On the Practices strip, today's square is an outline until you keep the habit; only kept fills. A streak not yet kept today shows a grey flame and says \"not yet today\", on Practices and on Today's chips.",
      "With the range on Month, the strip now draws the whole first and last week, so a Wednesday kept on 30 Sep shows under October's first week. The totals and the rate still count the month alone.",
      "Day labels read M T W Th F Sa Su on every strip, and Sun to Sat on the habit's days.",
    ],
    audience: "everyone",
  },
  {
    n: 45,
    date: "2026-10-01",
    title: "HumanOS: mark a travel or sick day, and the week in a paragraph",
    lines: ["On Log, under \"Change this day's type or mark it\", mark a day Travelling or Ill. Patterns can leave those days out, alongside days with an open injury, so a bad week away doesn't pass for a pattern.", "On This week, \"Summarise this week\" asks your own AI for one paragraph on the week's numbers (days in band, averages, sessions, weight, sleep, habits). It gets numbers only, never a food, a note or a photo, and the paragraph is shown, not saved. Only with \"Let AI use my HumanOS data\" on."],
    audience: "everyone",
  },
  {
    n: 44,
    date: "2026-10-01",
    title: "Picture suggestions that name what to show",
    lines: [
      "The Deck step now suggests a picture from what the slide says: a line with a figure (\"602 comments on my post\", \"98.2% opened\", \"$114,400\") asks for a screenshot with that figure circled; a line naming your framework, system or funnel asks for your own diagram; before and after asks for the two photos; comments or DMs ask for a wall of them. A line that names nothing to show asks for nothing.",
      "The cover asks for a photo of you on stage or on a call, each origin beat names its moment, and a story asks for the person it is about. Suggestions are spread out: never more than two picture slides in a row.",
    ],
    audience: "everyone",
  },
  {
    n: 43,
    date: "2026-10-01",
    title: "Slides say your words, never the wizard's labels",
    lines: [
      "No slide carries a section or act label any more (\"Case Study · Vehicle\", \"Act 1 · Vehicle · recap\", \"A moment before we go on\"). A divider says the belief's own shift, a recap repeats the act's lines under it, and the section name sits in the speaker notes where you find your place.",
      "A story is told, not titled: its bank title goes to the notes and the story runs as beats, one sentence per slide, with the picture slot on the first beat.",
    ],
    audience: "everyone",
  },
  {
    n: 42,
    date: "2026-10-01",
    title: "Empty picture slots show in red",
    lines: ["A slide whose suggested picture you haven't added now exports with a dashed frame and red text saying what to add there (\"Add a photo: you or the person in this beat.\"), instead of quietly dropping to text. Attach the picture and it fills that same frame; nothing else on the slide moves. The Deck step lists the empty slots, as before."],
    audience: "everyone",
  },
  {
    n: 41,
    date: "2026-10-01",
    title: "The month's thread, in the post's own shape",
    lines: [
      "Share your month copies your eleven answers numbered the way the month's post numbers its questions, so your comment reads like the post. The month post's title is now \"Set Your Intentions November 2026\".",
      "Coaches: the month post (and the Monday one) can carry a graphic from your Images library, picked under Setup on Community posts; a square 540 by 540 image is sent at the bottom of the post. New clients start with \"Let my coach work in my HelixOS\" on, every tier, and can turn it off in Settings; the roster marks who has.",
    ],
    audience: "everyone",
  },
  {
    n: 40,
    date: "2026-10-01",
    title: "Deck pictures keep their shape",
    lines: [
      "A photo on a slide now fills its frame and is cropped to it, never squeezed or stretched; a screenshot, proof image or logo is shown whole at its own shape inside the frame, so the number in it is never cut off. Nothing is drawn larger than the picture really is.",
      "The file is smaller: pictures are downscaled to what a slide needs and a photo is saved as a JPEG, and a picture used on several slides (your logo on every slide) is stored once.",
    ],
    audience: "everyone",
  },
  {
    n: 39,
    date: "2026-10-01",
    title: "HumanOS: log a meal from a photo",
    lines: ["On Log, \"From a photo\" takes a picture of your plate and your own AI names the foods and guesses the portions and macros. You check every line, fix the amounts, untick what isn't there, and press Log these. Nothing is logged before that, the photo is never kept, and it works only with \"Let AI use my HumanOS data\" on and your own AI key."],
    audience: "everyone",
  },
  {
    n: 38,
    date: "2026-10-01",
    title: "Share your month to the community thread",
    lines: [
      "Under your set month on Intentions, one tap copies your eleven answers and opens this month's post in the community, where you paste them as a comment under your own name. 15 points, once a month. \"This month's thread\" sits beside the heading once the post is up.",
      "Coaches: the first-of-the-month post has its own switch, time and text on Community posts, beside the Monday one, and goes out on the 1st. A month you posted by hand takes its pasted link, so the share works for it too. The coach view's month card counts who has shared.",
    ],
    audience: "everyone",
  },
  {
    n: 37,
    date: "2026-10-01",
    title: "HumanOS: a coach's day view with sleep and practices, and four small fixes",
    lines: ["When a client shares HumanOS with you, their day now shows last night's sleep and recovery and the practices they kept, beside the meals and the workout. Their health log stays theirs.", "Training has a date picker to log a missed day on its date; a PR set today is today's PR in the day's summary and in Claude's answer; the routine form grows with Add rows; and the Airtable page offers a day-types-only import for a member whose history is already in."],
    audience: "coach",
  },
  {
    n: 36,
    date: "2026-10-01",
    title: "Turn on HumanOS yourself",
    lines: ["Settings has a HumanOS card with one switch: turn it on and the HumanOS section (Log, Nutrition, Training, Sleep, Practices) appears in your menu, with everything in it private to you. Turn it off and it hides again; nothing is deleted. While it's off, the menu shows one entry that takes you to the switch.", "Your coach can turn it on for you from their coach view when you've given them working access in Settings; it shares nothing with them, and sharing stays your own choice inside HumanOS settings.", "Everywhere you read, the name is HumanOS now; your pages and links are unchanged."],
    audience: "everyone",
  },
  {
    n: 35,
    date: "2026-10-01",
    title: "HumanOS: find a food by name or barcode",
    lines: ["Nutrition has a Find a food page: search the USDA food database by name, or look a product up by the number under its barcode (or scan it with your phone's camera). Each result shows its calories, protein, fat, carbs and sodium per 100 g, and Save to my foods adds it per your own unit, with the store section and raw/cooked basis guessed for you to fix. Nothing saves until you press Save."],
    audience: "coach",
  },
  {
    n: 34,
    date: "2026-10-01",
    title: "Coach view: a HumanOS column",
    lines: ["The client table has a HumanOS column for clients who share their HumanOS data with you: days in band this week, their last weigh-in, and sessions this week, linking to their days. Clients who don't share show nothing there, the same as clients without HumanOS."],
    audience: "coach",
  },
  {
    n: 33,
    date: "2026-10-01",
    title: "HumanOS: WHOOP",
    lines: ["Connect WHOOP from HumanOS settings and it fills Sleep (hours and score), recovery, strain, resting heart rate and HRV, and brings every workout by its sport with its minutes, strain and heart rate onto Training. A sport that is one of your habits (sauna, stretching, walking, yoga…) ticks it for the day; what you logged by hand stays.", "WHOOP sends changes as they happen, and Sync now pulls the last 30 days. The connection is yours alone: Disconnect removes it, and your coach never sees any of it unless you share the rest."],
    audience: "coach",
  },
  {
    n: 32,
    date: "2026-10-01",
    title: "HumanOS: the longer view",
    lines: ["One range picker on the week page, Sleep and Practices: Week, Month, 90 days or a Year, stepped back and forward, and bookmarkable. Past a week, the week page shows the same tiles over the range with sessions a week as bars, the calendar of trained days, which routines ran how often, PRs set in the range, weight and body fat change, sleep a night and habits kept.", "Sleep gets its nights as a bar strip with the average, nights at 7 h and under, by week. Practices gets kept days per habit as a heat strip with the kept rate and the best run. An exercise's history reads over 90 days, a year or all. Claude's tools take the same range."],
    audience: "coach",
  },
  {
    n: 31,
    date: "2026-10-01",
    title: "HumanOS: the shopping list and Instacart",
    lines: ["From Pantry, a Shopping list: pick the saved meals you'll eat this week and how many times, and the list is what they need minus what's on your shelf, plus any staple below its par level, grouped by store section (set on each food). Mark a line bought and it lands on the shelf.", "Push to Instacart turns the list into an Instacart shopping-list page and gives you the link: you pick the store, review, add to cart and pay in Instacart yourself. HelixOS never places or pays for an order. Every push is logged. Claude can read the list and, once you confirm, send it the same way."],
    audience: "coach",
  },
  {
    n: 30,
    date: "2026-10-01",
    title: "HumanOS: Patterns",
    lines: ["From your week, a Patterns page: pick any two of your numbers (sleep, weight, calories, workouts, a habit, or a business number from your daily log such as calls booked or cash collected), with B read up to three days after A, over 4, 8 or 12 weeks, daily or weekly, and see them on one timeline, each pair as a dot, and an honest readout.", "The readout always gives r with the number of paired days, says nothing under 21, calls 21 to 41 an early signal, and names a pattern only when it holds in both halves of the range. Moving together is never called a cause. Seven presets to start, and Claude can ask the same question."],
    audience: "coach",
  },
  {
    n: 29,
    date: "2026-10-01",
    title: "HumanOS: Sleep, Practices and the health log",
    lines: ["Two more HumanOS pages, so the menu reaches its five. Practices: habits from a starter list or your own (done, minutes, a count or an amount), a daily target and the days it applies, one tap to log, a streak that forgives one missed day a week, and the week's dots; the ones due today sit as one-tap chips on Today. Sleep: last night's hours and an optional score, the week against last, nights at 7 h, a 30-night trend.", "Under Training, a health log: an injury, since when, which side, the movements it affects and the exercises to leave out, which Training then marks. It is yours alone: never your coach, even while you share the rest; never AI or Claude; never in anything sent to them. Sleep and habits kept join your week, the AI's numbers, and Claude's tools."],
    audience: "coach",
  },
  {
    n: 28,
    date: "2026-09-30",
    title: "HumanOS: your history from Airtable",
    lines: ["A \"From Airtable\" page (from Weigh-ins, Training and HumanOS settings) brings your HumanOS base over: every weigh-in as one reading a day, your routines, and your workouts as sets, from the Exercises rows where a day has them and from the working-set lines of your Exercise Notes where it doesn't.", "Paste the base id and a read-only token, see the dry run day by day, then Approve. The token is used for that run only and kept nowhere; the notes' words stay in Airtable. Run it again any time: nothing lands twice."],
    audience: "coach",
  },
  {
    n: 27,
    date: "2026-09-30",
    title: "HumanOS: your week",
    lines: ["A \"This week\" page from Log and Training: days logged and in band, average calories, protein against its floor and fat against its ceiling, sessions of those planned with sets and PRs, your average weight and its change against last week, and whether your weight goal is on pace.", "Step back a week at a time; every figure is computed from your days, never stored. In Claude, ask for \"my week\"."],
    audience: "coach",
  },
  {
    n: 26,
    date: "2026-09-30",
    title: "Tasks brought over from Airtable wait for you",
    lines: ["If your coach brought your tasks over from Airtable, they wait on Tasks under \"From Airtable, to review\", with their dates as written there, and stay off Today until you keep them.", "Keep makes one yours, Done files it as history, and Let go hides it without deleting it. One button keeps every one dated after today."],
    audience: "everyone",
  },
  {
    n: 25,
    date: "2026-09-30",
    title: "HumanOS: Pantry",
    lines: ["A Pantry under Nutrition: what's on the shelf (how much, raw or cooked, where, use by), what to use within two days (shown on Log too, and those meals come first in what fits), and what to buy when a food drops below the par level you give it.", "Logging a meal takes its foods off the shelf. Foods are counted cooked; weigh a food raw and cooked and its yield is learned, so logging raw converts. Caps can be per week and say when they open again."],
    audience: "coach",
  },
  {
    n: 24,
    date: "2026-09-30",
    title: "HumanOS in Claude",
    lines: ["With HumanOS's AI switch on and the HumanOS area ticked when you connect HelixOS to Claude, Claude can read your day (targets, what you've eaten, what's left and what fits), your foods, your weigh-ins and your training.", "It can also log for you: a saved meal or a food, a set, a weigh-in. Never your photos, injuries or what your coach wrote."],
    audience: "coach",
  },
  {
    n: 23,
    date: "2026-09-30",
    title: "HumanOS: finish your workout",
    lines: ["Training now counts your sets against the routine's plan (\"5 of 9 planned sets\", \"1 of 3 sets · 8–10 reps\" per exercise, a set under its reps marked), and a Finish workout button stamps the session done with an optional note. Logging another set reopens it.", "A Consistency card shows the last 12 weeks as a heatmap and \"3 of 5 sessions this week\", counting the days whose day type has a routine."],
    audience: "coach",
  },
  {
    n: 22,
    date: "2026-09-30",
    title: "HumanOS: Weigh-ins",
    lines: ["Log your weight and what the scale shows with it, or import your RENPHO export (either layout; readings already in are skipped). The day's figure is its lowest reading, kept whole.", "Trend cards for weight, body fat, fat-free mass and the rest, with a 7-day average, a goal line you set, and 30-day to all-time views. The Log page shows your latest weigh-in."],
    audience: "coach",
  },
  {
    n: 21,
    date: "2026-09-30",
    title: "Connect HelixOS to Claude",
    lines: ["Add HelixOS as a connector in Claude and it can read your HelixOS from a chat, acting only as you, with only the areas you tick. Settings shows every connected app with Disconnect, which cuts it at once. See Connect HelixOS to Claude in the More menu for the address and the steps.", "This first release answers who you are; tools for Today, tasks, offers and more follow."],
    audience: "everyone",
  },
  {
    n: 20,
    date: "2026-09-30",
    title: "HumanOS: Training",
    lines: ["Training is new under HumanOS. Add your exercises, group them into routines, and tie a routine to a day type so it's offered on those days.", "Log each set as weight × reps. Last time's sets and your PR sit beside each exercise, a new PR gets a 🏆, and each exercise has a history chart. Rest days can be marked Off."],
    audience: "coach",
  },
  {
    n: 19,
    date: "2026-09-30",
    title: "Chat with your coach's assistant",
    lines: ["When your coach has set it up, their assistant's chat bubble is on every page, and it knows it's you. A conversation you start here can carry on in Messenger, Instagram or WhatsApp: the assistant sends a \"confirm it's you\" link, you tap it, and Settings lists the linked chat with Unlink.", "It gets your name and email, and never HumanOS."],
    audience: "everyone",
  },
  {
    n: 18,
    date: "2026-09-29",
    title: "Body is now HumanOS",
    lines: ["HumanOS has its own section in the menu: Log for today's meals and Nutrition for your foods and saved meals. A gear on every HumanOS page opens its settings.", "Log leads with what's left (\"62 g protein to go · 14 g fat left\"), puts your saved meals and recent foods first, and Today has a Log a meal button. Old links still work."],
    audience: "coach",
  },
  {
    n: 17,
    date: "2026-09-29",
    title: "Let your coach set things up for you",
    lines: ["In Settings, \"Let my coach work in my HelixOS\" lets your coach set up offers, webinars, tasks and more for you. It's your choice, and you can switch it off any time.", "Everything they change is listed under \"Changes by your coach\". They never see HumanOS, send anything as you, or change your account."],
    audience: "everyone",
  },
  {
    n: 16,
    date: "2026-09-29",
    title: "Switch to a client",
    lines: ["On a client's page (or the client list), \"Switch to\" opens their HelixOS exactly as they see it. A banner says whose it is, with Back to my account.", "View looks without changing anything. Work in their HelixOS sets things up for them, when they've allowed it, and every change is shown to them."],
    audience: "coach",
  },
  {
    n: 15,
    date: "2026-09-29",
    title: "HumanOS: pick units from a list, and sodium on foods",
    lines: ["A food's \"per\" unit is picked from a list (oz, g, cup, slice and more), or Other for anything else. Log a food in another unit of the same kind, such as grams for a food counted in ounces, and it converts.", "Foods take sodium and a tag for caps, and your day shows its sodium. Download and delete-all are now two separate boxes in HumanOS settings."],
    audience: "coach",
  },
  {
    n: 14,
    date: "2026-09-29",
    title: "HumanOS: choose whether AI can help you",
    lines: ["The first step of HumanOS asks whether HelixOS's AI may use your HumanOS numbers (targets, what you logged, your saved meals) to support you. Yes or Not now; it stays off unless you say Yes.", "Never your photos or notes, and always on your own AI key. You can change it any time in HumanOS settings, and every change is logged."],
    audience: "coach",
  },
  {
    n: 13,
    date: "2026-09-29",
    title: "HumanOS (beta), just for you for now",
    lines: ["Nutrition targets and fast meal logging: day types with their own bands, your foods and saved meals, a mark on each macro, and \"What fits tonight?\".", "Switch it on in Settings under HumanOS (beta). It starts empty, with a short checklist to fill it in. Your HumanOS data is private: nobody else sees it unless you share it."],
    audience: "coach",
    version: "b9ed9be",
  },
  {
    n: 12,
    date: "2026-09-29",
    title: "@everyone in the Monday post is a real tag",
    lines: ["The Monday post's @everyone now shows as a tag in the community, the way it does when you post by hand. Test posts keep it as plain words, so they never ping the group."],
    audience: "coach",
  },
  {
    n: 11,
    date: "2026-09-29",
    title: "What's new, and the version you're on",
    lines: ["This page lists what changed in HelixOS, newest first. The menu shows a small dot when there's something you haven't seen.", "The version you're using is at the bottom of the menu and of Settings."],
    audience: "everyone",
  },
  {
    n: 10,
    date: "2026-09-29",
    title: "The Monday post keeps its layout and can notify everyone",
    lines: ["The Monday 3-1-3 post keeps its paragraphs and line breaks.", "\"Send the Monday text as a test\" shows the layout in your test channel first.", "\"Notify all members\" (on by default) tells the whole group when the Monday post goes out. Tests never notify anyone."],
    audience: "coach",
    version: "7fa6b38",
  },
  {
    n: 9,
    date: "2026-09-29",
    title: "You choose who gets emails from HelixOS",
    lines: ["Each client's page has an \"Emails from HelixOS\" switch. Nobody gets an automated email before their first sign-in.", "A client you import starts with emails off, so they hear nothing until you've introduced HelixOS."],
    audience: "coach",
    version: "1f411b4",
  },
  {
    n: 8,
    date: "2026-09-28",
    title: "Share to the thread is one big button",
    lines: ["Once your week is set, one tap copies your 3-1-3 and opens this week's post. Paste it as a comment and press Post.", "\"This week's thread →\" at the top of Intentions takes you to the post any time, even before your week is set."],
    audience: "everyone",
    version: "63da340",
  },
  {
    n: 7,
    date: "2026-09-28",
    title: "The Monday post goes to your community by itself",
    lines: ["Community posts (under Grow) posts the \"Set Your Intentions\" thread every Monday, shows each week's post, and who has shared to it."],
    audience: "coach",
    version: "e3ee339",
  },
  {
    n: 6,
    date: "2026-09-28",
    title: "Add several tasks before you lock in",
    lines: ["On Today, add new tasks one after another with Add or Enter, then tick your top 3 and lock in."],
    audience: "everyone",
    version: "06fe2ca",
  },
  {
    n: 5,
    date: "2026-09-28",
    title: "A green \"Saved ✓\" on every save, and nothing you type is lost",
    lines: ["Every save shows a short green confirmation.", "If something needs fixing, what you typed stays in the form and the field to fix is marked."],
    audience: "everyone",
    version: "06fe2ca",
  },
  {
    n: 4,
    date: "2026-09-28",
    title: "Your week and month live on Intentions",
    lines: ["Setting your week, your month and the monthly feedback moved from Today to Intentions. A small dot on Intentions tells you when one is due."],
    audience: "everyone",
    version: "06fe2ca",
  },
  {
    n: 3,
    date: "2026-09-27",
    title: "Import a client from Airtable",
    lines: ["Coach → Import from Airtable reads a client's base, shows you everything it found first, and brings it in once you approve."],
    audience: "coach",
    version: "af265f4",
  },
  {
    n: 2,
    date: "2026-09-26",
    title: "Your monthly intention",
    lines: ["From the 1st, set your month: your word, your season, and what you're building toward. Your past months stay on Intentions."],
    audience: "everyone",
    version: "bbb8636",
  },
  {
    n: 1,
    date: "2026-09-25",
    title: "The weekly 3-1-3",
    lines: ["Each week: one word, three key results you can count, one initiative and three tasks. Your tasks land on your list, due Friday."],
    audience: "everyone",
    version: "47c33b9",
  },
];
