/**
 * What's new (rev 193): what changed for members and coaches, newest first, in plain words. Kept here as data and reviewed like
 * code, never edited in the app. Every commit that changes what someone sees adds its entry in the same commit (the gate
 * checks, src/lib/engine/whats-new.ts); refactors, tests and internal fixes don't.
 *
 * `n` only ever grows: the next entry takes the highest `n` plus one. It is how the menu's dot knows what a member hasn't seen.
 * `version` is the commit it arrived in when known; an entry written in the same commit as its change can't name that commit,
 * so it shows the day's version instead.
 */
export type Audience = "everyone" | "coach";
export type WhatsNewEntry = { n: number; date: string; title: string; lines: string[]; audience: Audience; version?: string };

export const WHATS_NEW: WhatsNewEntry[] = [
  {
    n: 44,
    date: "2026-10-01",
    title: "Picture suggestions that name what to show",
    lines: [
      "The Deck step now suggests a picture from what the slide says: a line with a figure (\"602 comments on my post\", \"98.2% opened\", \"$114,400\") asks for a screenshot with that figure circled; a line naming your framework, system or funnel asks for your own diagram; before and after asks for the two photos; comments or DMs ask for a wall of them. A line that names nothing to show asks for nothing.",
      "The cover asks for a photo of you on stage or on a call, each origin beat names its moment, and a story asks for the person it is about. Suggestions are spread out: never more than two picture slides in a row.",
    ],
    audience: "everyone",
  },
  {
    n: 43,
    date: "2026-10-01",
    title: "Slides say your words, never the wizard's labels",
    lines: [
      "No slide carries a section or act label any more (\"Case Study · Vehicle\", \"Act 1 · Vehicle · recap\", \"A moment before we go on\"). A divider says the belief's own shift, a recap repeats the act's lines under it, and the section name sits in the speaker notes where you find your place.",
      "A story is told, not titled: its bank title goes to the notes and the story runs as beats, one sentence per slide, with the picture slot on the first beat.",
    ],
    audience: "everyone",
  },
  {
    n: 42,
    date: "2026-10-01",
    title: "Empty picture slots show in red",
    lines: ["A slide whose suggested picture you haven't added now exports with a dashed frame and red text saying what to add there (\"Add a photo: you or the person in this beat.\"), instead of quietly dropping to text. Attach the picture and it fills that same frame; nothing else on the slide moves. The Deck step lists the empty slots, as before."],
    audience: "everyone",
  },
  {
    n: 41,
    date: "2026-10-01",
    title: "The month's thread, in the post's own shape",
    lines: [
      "Share your month copies your eleven answers numbered the way the month's post numbers its questions, so your comment reads like the post. The month post's title is now \"Set Your Intentions November 2026\".",
      "Coaches: the month post (and the Monday one) can carry a graphic from your Images library, picked under Setup on Community posts; a square 540 by 540 image is sent at the bottom of the post. New clients start with \"Let my coach work in my HelixOS\" on, every tier, and can turn it off in Settings; the roster marks who has.",
    ],
    audience: "everyone",
  },
  {
    n: 40,
    date: "2026-10-01",
    title: "Deck pictures keep their shape",
    lines: [
      "A photo on a slide now fills its frame and is cropped to it, never squeezed or stretched; a screenshot, proof image or logo is shown whole at its own shape inside the frame, so the number in it is never cut off. Nothing is drawn larger than the picture really is.",
      "The file is smaller: pictures are downscaled to what a slide needs and a photo is saved as a JPEG, and a picture used on several slides (your logo on every slide) is stored once.",
    ],
    audience: "everyone",
  },
  {
    n: 39,
    date: "2026-10-01",
    title: "HumanOS: log a meal from a photo",
    lines: ["On Log, \"From a photo\" takes a picture of your plate and your own AI names the foods and guesses the portions and macros. You check every line, fix the amounts, untick what isn't there, and press Log these. Nothing is logged before that, the photo is never kept, and it works only with \"Let AI use my HumanOS data\" on and your own AI key."],
    audience: "everyone",
  },
  {
    n: 38,
    date: "2026-10-01",
    title: "Share your month to the community thread",
    lines: [
      "Under your set month on Intentions, one tap copies your eleven answers and opens this month's post in the community, where you paste them as a comment under your own name. 15 points, once a month. \"This month's thread\" sits beside the heading once the post is up.",
      "Coaches: the first-of-the-month post has its own switch, time and text on Community posts, beside the Monday one, and goes out on the 1st. A month you posted by hand takes its pasted link, so the share works for it too. The coach view's month card counts who has shared.",
    ],
    audience: "everyone",
  },
  {
    n: 37,
    date: "2026-10-01",
    title: "HumanOS: a coach's day view with sleep and practices, and four small fixes",
    lines: ["When a client shares HumanOS with you, their day now shows last night's sleep and recovery and the practices they kept, beside the meals and the workout. Their health log stays theirs.", "Training has a date picker to log a missed day on its date; a PR set today is today's PR in the day's summary and in Claude's answer; the routine form grows with Add rows; and the Airtable page offers a day-types-only import for a member whose history is already in."],
    audience: "coach",
  },
  {
    n: 36,
    date: "2026-10-01",
    title: "Turn on HumanOS yourself",
    lines: ["Settings has a HumanOS card with one switch: turn it on and the HumanOS section (Log, Nutrition, Training, Sleep, Practices) appears in your menu, with everything in it private to you. Turn it off and it hides again; nothing is deleted. While it's off, the menu shows one entry that takes you to the switch.", "Your coach can turn it on for you from their coach view when you've given them working access in Settings; it shares nothing with them, and sharing stays your own choice inside HumanOS settings.", "Everywhere you read, the name is HumanOS now; your pages and links are unchanged."],
    audience: "everyone",
  },
  {
    n: 35,
    date: "2026-10-01",
    title: "HumanOS: find a food by name or barcode",
    lines: ["Nutrition has a Find a food page: search the USDA food database by name, or look a product up by the number under its barcode (or scan it with your phone's camera). Each result shows its calories, protein, fat, carbs and sodium per 100 g, and Save to my foods adds it per your own unit, with the store section and raw/cooked basis guessed for you to fix. Nothing saves until you press Save."],
    audience: "coach",
  },
  {
    n: 34,
    date: "2026-10-01",
    title: "Coach view: a HumanOS column",
    lines: ["The client table has a HumanOS column for clients who share their HumanOS data with you: days in band this week, their last weigh-in, and sessions this week, linking to their days. Clients who don't share show nothing there, the same as clients without HumanOS."],
    audience: "coach",
  },
  {
    n: 33,
    date: "2026-10-01",
    title: "HumanOS: WHOOP",
    lines: ["Connect WHOOP from HumanOS settings and it fills Sleep (hours and score), recovery, strain, resting heart rate and HRV, and brings every workout by its sport with its minutes, strain and heart rate onto Training. A sport that is one of your habits (sauna, stretching, walking, yoga…) ticks it for the day; what you logged by hand stays.", "WHOOP sends changes as they happen, and Sync now pulls the last 30 days. The connection is yours alone: Disconnect removes it, and your coach never sees any of it unless you share the rest."],
    audience: "coach",
  },
  {
    n: 32,
    date: "2026-10-01",
    title: "HumanOS: the longer view",
    lines: ["One range picker on the week page, Sleep and Practices: Week, Month, 90 days or a Year, stepped back and forward, and bookmarkable. Past a week, the week page shows the same tiles over the range with sessions a week as bars, the calendar of trained days, which routines ran how often, PRs set in the range, weight and body fat change, sleep a night and habits kept.", "Sleep gets its nights as a bar strip with the average, nights at 7 h and under, by week. Practices gets kept days per habit as a heat strip with the kept rate and the best run. An exercise's history reads over 90 days, a year or all. Claude's tools take the same range."],
    audience: "coach",
  },
  {
    n: 31,
    date: "2026-10-01",
    title: "HumanOS: the shopping list and Instacart",
    lines: ["From Pantry, a Shopping list: pick the saved meals you'll eat this week and how many times, and the list is what they need minus what's on your shelf, plus any staple below its par level, grouped by store section (set on each food). Mark a line bought and it lands on the shelf.", "Push to Instacart turns the list into an Instacart shopping-list page and gives you the link: you pick the store, review, add to cart and pay in Instacart yourself. HelixOS never places or pays for an order. Every push is logged. Claude can read the list and, once you confirm, send it the same way."],
    audience: "coach",
  },
  {
    n: 30,
    date: "2026-10-01",
    title: "HumanOS: Patterns",
    lines: ["From your week, a Patterns page: pick any two of your numbers (sleep, weight, calories, workouts, a habit, or a business number from your daily log such as calls booked or cash collected), with B read up to three days after A, over 4, 8 or 12 weeks, daily or weekly, and see them on one timeline, each pair as a dot, and an honest readout.", "The readout always gives r with the number of paired days, says nothing under 21, calls 21 to 41 an early signal, and names a pattern only when it holds in both halves of the range. Moving together is never called a cause. Seven presets to start, and Claude can ask the same question."],
    audience: "coach",
  },
  {
    n: 29,
    date: "2026-10-01",
    title: "HumanOS: Sleep, Practices and the health log",
    lines: ["Two more HumanOS pages, so the menu reaches its five. Practices: habits from a starter list or your own (done, minutes, a count or an amount), a daily target and the days it applies, one tap to log, a streak that forgives one missed day a week, and the week's dots; the ones due today sit as one-tap chips on Today. Sleep: last night's hours and an optional score, the week against last, nights at 7 h, a 30-night trend.", "Under Training, a health log: an injury, since when, which side, the movements it affects and the exercises to leave out, which Training then marks. It is yours alone: never your coach, even while you share the rest; never AI or Claude; never in anything sent to them. Sleep and habits kept join your week, the AI's numbers, and Claude's tools."],
    audience: "coach",
  },
  {
    n: 28,
    date: "2026-09-30",
    title: "HumanOS: your history from Airtable",
    lines: ["A \"From Airtable\" page (from Weigh-ins, Training and HumanOS settings) brings your HumanOS base over: every weigh-in as one reading a day, your routines, and your workouts as sets, from the Exercises rows where a day has them and from the working-set lines of your Exercise Notes where it doesn't.", "Paste the base id and a read-only token, see the dry run day by day, then Approve. The token is used for that run only and kept nowhere; the notes' words stay in Airtable. Run it again any time: nothing lands twice."],
    audience: "coach",
  },
  {
    n: 27,
    date: "2026-09-30",
    title: "HumanOS: your week",
    lines: ["A \"This week\" page from Log and Training: days logged and in band, average calories, protein against its floor and fat against its ceiling, sessions of those planned with sets and PRs, your average weight and its change against last week, and whether your weight goal is on pace.", "Step back a week at a time; every figure is computed from your days, never stored. In Claude, ask for \"my week\"."],
    audience: "coach",
  },
  {
    n: 26,
    date: "2026-09-30",
    title: "Tasks brought over from Airtable wait for you",
    lines: ["If your coach brought your tasks over from Airtable, they wait on Tasks under \"From Airtable, to review\", with their dates as written there, and stay off Today until you keep them.", "Keep makes one yours, Done files it as history, and Let go hides it without deleting it. One button keeps every one dated after today."],
    audience: "everyone",
  },
  {
    n: 25,
    date: "2026-09-30",
    title: "HumanOS: Pantry",
    lines: ["A Pantry under Nutrition: what's on the shelf (how much, raw or cooked, where, use by), what to use within two days (shown on Log too, and those meals come first in what fits), and what to buy when a food drops below the par level you give it.", "Logging a meal takes its foods off the shelf. Foods are counted cooked; weigh a food raw and cooked and its yield is learned, so logging raw converts. Caps can be per week and say when they open again."],
    audience: "coach",
  },
  {
    n: 24,
    date: "2026-09-30",
    title: "HumanOS in Claude",
    lines: ["With HumanOS's AI switch on and the HumanOS area ticked when you connect HelixOS to Claude, Claude can read your day (targets, what you've eaten, what's left and what fits), your foods, your weigh-ins and your training.", "It can also log for you: a saved meal or a food, a set, a weigh-in. Never your photos, injuries or what your coach wrote."],
    audience: "coach",
  },
  {
    n: 23,
    date: "2026-09-30",
    title: "HumanOS: finish your workout",
    lines: ["Training now counts your sets against the routine's plan (\"5 of 9 planned sets\", \"1 of 3 sets · 8–10 reps\" per exercise, a set under its reps marked), and a Finish workout button stamps the session done with an optional note. Logging another set reopens it.", "A Consistency card shows the last 12 weeks as a heatmap and \"3 of 5 sessions this week\", counting the days whose day type has a routine."],
    audience: "coach",
  },
  {
    n: 22,
    date: "2026-09-30",
    title: "HumanOS: Weigh-ins",
    lines: ["Log your weight and what the scale shows with it, or import your RENPHO export (either layout; readings already in are skipped). The day's figure is its lowest reading, kept whole.", "Trend cards for weight, body fat, fat-free mass and the rest, with a 7-day average, a goal line you set, and 30-day to all-time views. The Log page shows your latest weigh-in."],
    audience: "coach",
  },
  {
    n: 21,
    date: "2026-09-30",
    title: "Connect HelixOS to Claude",
    lines: ["Add HelixOS as a connector in Claude and it can read your HelixOS from a chat, acting only as you, with only the areas you tick. Settings shows every connected app with Disconnect, which cuts it at once. See Connect HelixOS to Claude in the More menu for the address and the steps.", "This first release answers who you are; tools for Today, tasks, offers and more follow."],
    audience: "everyone",
  },
  {
    n: 20,
    date: "2026-09-30",
    title: "HumanOS: Training",
    lines: ["Training is new under HumanOS. Add your exercises, group them into routines, and tie a routine to a day type so it's offered on those days.", "Log each set as weight × reps. Last time's sets and your PR sit beside each exercise, a new PR gets a 🏆, and each exercise has a history chart. Rest days can be marked Off."],
    audience: "coach",
  },
  {
    n: 19,
    date: "2026-09-30",
    title: "Chat with your coach's assistant",
    lines: ["When your coach has set it up, their assistant's chat bubble is on every page, and it knows it's you. A conversation you start here can carry on in Messenger, Instagram or WhatsApp: the assistant sends a \"confirm it's you\" link, you tap it, and Settings lists the linked chat with Unlink.", "It gets your name and email, and never HumanOS."],
    audience: "everyone",
  },
  {
    n: 18,
    date: "2026-09-29",
    title: "Body is now HumanOS",
    lines: ["HumanOS has its own section in the menu: Log for today's meals and Nutrition for your foods and saved meals. A gear on every HumanOS page opens its settings.", "Log leads with what's left (\"62 g protein to go · 14 g fat left\"), puts your saved meals and recent foods first, and Today has a Log a meal button. Old links still work."],
    audience: "coach",
  },
  {
    n: 17,
    date: "2026-09-29",
    title: "Let your coach set things up for you",
    lines: ["In Settings, \"Let my coach work in my HelixOS\" lets your coach set up offers, webinars, tasks and more for you. It's your choice, and you can switch it off any time.", "Everything they change is listed under \"Changes by your coach\". They never see HumanOS, send anything as you, or change your account."],
    audience: "everyone",
  },
  {
    n: 16,
    date: "2026-09-29",
    title: "Switch to a client",
    lines: ["On a client's page (or the client list), \"Switch to\" opens their HelixOS exactly as they see it. A banner says whose it is, with Back to my account.", "View looks without changing anything. Work in their HelixOS sets things up for them, when they've allowed it, and every change is shown to them."],
    audience: "coach",
  },
  {
    n: 15,
    date: "2026-09-29",
    title: "HumanOS: pick units from a list, and sodium on foods",
    lines: ["A food's \"per\" unit is picked from a list (oz, g, cup, slice and more), or Other for anything else. Log a food in another unit of the same kind, such as grams for a food counted in ounces, and it converts.", "Foods take sodium and a tag for caps, and your day shows its sodium. Download and delete-all are now two separate boxes in HumanOS settings."],
    audience: "coach",
  },
  {
    n: 14,
    date: "2026-09-29",
    title: "HumanOS: choose whether AI can help you",
    lines: ["The first step of HumanOS asks whether HelixOS's AI may use your HumanOS numbers (targets, what you logged, your saved meals) to support you. Yes or Not now; it stays off unless you say Yes.", "Never your photos or notes, and always on your own AI key. You can change it any time in HumanOS settings, and every change is logged."],
    audience: "coach",
  },
  {
    n: 13,
    date: "2026-09-29",
    title: "HumanOS (beta), just for you for now",
    lines: ["Nutrition targets and fast meal logging: day types with their own bands, your foods and saved meals, a mark on each macro, and \"What fits tonight?\".", "Switch it on in Settings under HumanOS (beta). It starts empty, with a short checklist to fill it in. Your HumanOS data is private: nobody else sees it unless you share it."],
    audience: "coach",
    version: "b9ed9be",
  },
  {
    n: 12,
    date: "2026-09-29",
    title: "@everyone in the Monday post is a real tag",
    lines: ["The Monday post's @everyone now shows as a tag in the community, the way it does when you post by hand. Test posts keep it as plain words, so they never ping the group."],
    audience: "coach",
  },
  {
    n: 11,
    date: "2026-09-29",
    title: "What's new, and the version you're on",
    lines: ["This page lists what changed in HelixOS, newest first. The menu shows a small dot when there's something you haven't seen.", "The version you're using is at the bottom of the menu and of Settings."],
    audience: "everyone",
  },
  {
    n: 10,
    date: "2026-09-29",
    title: "The Monday post keeps its layout and can notify everyone",
    lines: ["The Monday 3-1-3 post keeps its paragraphs and line breaks.", "\"Send the Monday text as a test\" shows the layout in your test channel first.", "\"Notify all members\" (on by default) tells the whole group when the Monday post goes out. Tests never notify anyone."],
    audience: "coach",
    version: "7fa6b38",
  },
  {
    n: 9,
    date: "2026-09-29",
    title: "You choose who gets emails from HelixOS",
    lines: ["Each client's page has an \"Emails from HelixOS\" switch. Nobody gets an automated email before their first sign-in.", "A client you import starts with emails off, so they hear nothing until you've introduced HelixOS."],
    audience: "coach",
    version: "1f411b4",
  },
  {
    n: 8,
    date: "2026-09-28",
    title: "Share to the thread is one big button",
    lines: ["Once your week is set, one tap copies your 3-1-3 and opens this week's post. Paste it as a comment and press Post.", "\"This week's thread →\" at the top of Intentions takes you to the post any time, even before your week is set."],
    audience: "everyone",
    version: "63da340",
  },
  {
    n: 7,
    date: "2026-09-28",
    title: "The Monday post goes to your community by itself",
    lines: ["Community posts (under Grow) posts the \"Set Your Intentions\" thread every Monday, shows each week's post, and who has shared to it."],
    audience: "coach",
    version: "e3ee339",
  },
  {
    n: 6,
    date: "2026-09-28",
    title: "Add several tasks before you lock in",
    lines: ["On Today, add new tasks one after another with Add or Enter, then tick your top 3 and lock in."],
    audience: "everyone",
    version: "06fe2ca",
  },
  {
    n: 5,
    date: "2026-09-28",
    title: "A green \"Saved ✓\" on every save, and nothing you type is lost",
    lines: ["Every save shows a short green confirmation.", "If something needs fixing, what you typed stays in the form and the field to fix is marked."],
    audience: "everyone",
    version: "06fe2ca",
  },
  {
    n: 4,
    date: "2026-09-28",
    title: "Your week and month live on Intentions",
    lines: ["Setting your week, your month and the monthly feedback moved from Today to Intentions. A small dot on Intentions tells you when one is due."],
    audience: "everyone",
    version: "06fe2ca",
  },
  {
    n: 3,
    date: "2026-09-27",
    title: "Import a client from Airtable",
    lines: ["Coach → Import from Airtable reads a client's base, shows you everything it found first, and brings it in once you approve."],
    audience: "coach",
    version: "af265f4",
  },
  {
    n: 2,
    date: "2026-09-26",
    title: "Your monthly intention",
    lines: ["From the 1st, set your month: your word, your season, and what you're building toward. Your past months stay on Intentions."],
    audience: "everyone",
    version: "bbb8636",
  },
  {
    n: 1,
    date: "2026-09-25",
    title: "The weekly 3-1-3",
    lines: ["Each week: one word, three key results you can count, one initiative and three tasks. Your tasks land on your list, due Friday."],
    audience: "everyone",
    version: "47c33b9",
  },
];
