/** Comment ladders: facts profile → new skeleton (no Claude) → checklist blocks it → the finished demo ladder clears → live hour → Airtable copy → composer. */
import { chromium, type Page } from "@playwright/test";
import { mkdirSync } from "node:fs";

const base = process.argv[2] ?? "http://localhost:3000";
mkdirSync("screenshots", { recursive: true });

async function expectText(page: Page, text: string, label: string) {
  const re = new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
  // A page answers at once with its loading skeleton; it must clear within 3 seconds, then the text must be there.
  await page.locator('[data-testid="page-loading"]').waitFor({ state: "hidden", timeout: 3000 }).catch(async () => {
    await page.screenshot({ path: `screenshots/fail-stuck-${label.replace(/\W+/g, "-")}.png`, fullPage: true });
    throw new Error(`[${label}] loading skeleton still showing after 3s on ${page.url()}: a client would see no page`);
  });
  await page.getByText(re).filter({ visible: true }).first().waitFor({ timeout: 15000 }).catch(async () => {
    await page.screenshot({ path: `screenshots/fail-${label.replace(/\W+/g, "-")}.png`, fullPage: true });
    throw new Error(`[${label}] expected "${text}" on ${page.url()}`);
  });
}
async function submit(page: Page, selector: string) {
  await Promise.all([page.waitForResponse((r) => r.request().method() === "POST"), page.locator(selector).first().click()]);
  await page.waitForLoadState("networkidle");
  await page.waitForTimeout(400);
}
async function checks(page: Page): Promise<Record<string, boolean>> {
  const items = await page.locator('[data-testid="checklist"] li').evaluateAll((els) => els.map((e) => [e.getAttribute("data-check"), e.getAttribute("data-ok") === "1"]));
  return Object.fromEntries(items as [string, boolean][]);
}

async function main() {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium" });
  const failures: string[] = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1400, height: 950 } });
    await context.grantPermissions(["clipboard-read", "clipboard-write"], { origin: base });
    const page = await context.newPage();
    page.on("response", (r) => {
      if (r.status() >= 500) failures.push(`${r.status()} ${r.url()}`);
    });
    await page.goto(`${base}/login`);
    await page.click('button:has-text("As a client")');
    await page.waitForURL(/\/today/);

    // Facts profile (seeded for Maya): open, tweak, save
    await page.goto(`${base}/content/ladders/profile`);
    await expectText(page, "Your ladder facts", "profile page");
    if ((await page.inputValue('input[name="productName"]')) !== "The 90-Day Reset") throw new Error("seeded profile not loaded");
    await page.fill('textarea[name="bannedPhrases"]', "cheat day\nguilt-free\nskinny\nmagic pill");
    await submit(page, 'button:has-text("Save facts")');
    await page.waitForURL(/\/content\/ladders$/);
    console.log("✓ facts profile saved");

    // New ladder without Claude → skeleton, checklist blocks it
    await expectText(page, "Build the skeleton", "no-AI button");
    await page.selectOption('select[name="format"]', "loss_rebuild");
    await page.fill('input[name="topic"]', "If I lost every client tomorrow");
    await page.selectOption('select[name="keyword"]', "RESET");
    await submit(page, 'button:has-text("Build the skeleton")');
    await page.waitForURL(/\/content\/ladders\/[a-z0-9-]+$/i);
    await expectText(page, "skeleton, fill the blanks", "generated by scaffold");
    let c = await checks(page);
    if (c.placeholders !== false) throw new Error("skeleton should fail the placeholder check");
    if (c.cta !== true) throw new Error("skeleton CTA rung should already carry the keyword and fallback");
    if (!(await page.locator('button:has-text("Mark ready")').isDisabled())) throw new Error("Mark ready must be disabled while the checklist fails");
    // The gate is the server, not the button: force the submit past the disabled control and the action must refuse
    const { db, schema } = await import("@/db");
    const { eq } = await import("drizzle-orm");
    const ladderId = page.url().split("/").pop()!.split("?")[0];
    const notice = page.locator('[data-testid="publish-blocked"]');
    if (!(await notice.count())) throw new Error("no notice names the failing checks");
    const links = await notice.locator('[data-testid="blocker-link"]').evaluateAll((as) => as.map((a) => a.getAttribute("href")));
    if (!links.length || !links.every((h) => h?.startsWith("#check-"))) throw new Error(`blockers should link to their checks: ${links.join(", ")}`);
    for (const href of links) if (!(await page.locator(href!).count())) throw new Error(`blocker link ${href} has no target`);
    if (!(await page.locator('[data-testid="send-to-composer"]').isDisabled())) throw new Error("Send to composer must be held while the checklist fails");
    await page.locator('[data-testid="send-to-composer"]').evaluate((el) => el.removeAttribute("disabled"));
    await Promise.all([page.waitForResponse((r) => r.request().method() === "POST"), page.locator('[data-testid="send-to-composer"]').click()]);
    await page.waitForURL(/blocked=/, { timeout: 10000 });
    let row = await db.query.ladders.findFirst({ where: eq(schema.ladders.id, ladderId) });
    if (row?.contentItemId) throw new Error("a failing ladder was still sent to the composer");
    await expectText(page, "That didn't go out", "refusal named");
    const firstRung = page.locator('[data-testid="mark-rung"]').first();
    await firstRung.evaluate((el) => el.removeAttribute("disabled"));
    await Promise.all([page.waitForResponse((r) => r.request().method() === "POST"), firstRung.click()]);
    await page.waitForTimeout(600);
    row = await db.query.ladders.findFirst({ where: eq(schema.ladders.id, ladderId) });
    if (row?.rungs.some((r) => r.postedAt)) throw new Error("a rung of a failing ladder was marked posted");
    if (!(await page.locator('button:has-text("Copy for Airtable")').isDisabled())) throw new Error("copies must be held while the checklist fails");
    console.log("✓ publish gate: server refuses the composer send and a posted rung while checks fail; blockers named and linked; copies held");
    await page.goto(`${base}/content/ladders/${ladderId}`);
    // Edit the body to add comment bait and confirm it's caught after save
    await page.fill('textarea[name="copy"]', "If I lost every client tomorrow.\nComment RESET for the plan.");
    await submit(page, 'button:has-text("Save and re-check")');
    c = await checks(page);
    if (c.bait !== false || c.question !== false) throw new Error("comment bait / missing question not caught");
    await page.screenshot({ path: "screenshots/ld01-skeleton-checklist.png", fullPage: true });
    console.log("✓ skeleton built; checklist blocks placeholders, comment bait and a missing question");

    // The finished demo ladder clears the checklist
    await page.goto(`${base}/content/ladders`);
    await page.click('a:has-text("SKIN — Mistakes Ladder")');
    await page.waitForURL(/\/content\/ladders\/[a-z0-9-]+$/i);
    c = await checks(page);
    const failing = Object.entries(c).filter(([, ok]) => !ok).map(([k]) => k);
    if (failing.length) throw new Error(`demo ladder should clear the checklist, failing: ${failing.join(", ")}`);
    await expectText(page, "checklist", "checklist card");
    if (!(await page.locator('[data-testid="headline-preview"]').isVisible())) throw new Error("headline preview missing");
    console.log("✓ finished ladder clears every check");
    // A ready ladder edited into a failing state is a draft again; fixed, it can be marked ready
    const demoId = page.url().split("/").pop()!.split("?")[0];
    const cleanCopy = await page.locator('textarea[name="copy"]').inputValue();
    await page.fill('textarea[name="copy"]', `${cleanCopy}\nThe skinny version is in the comments?`);
    await submit(page, 'button:has-text("Save and re-check")');
    let demo = await db.query.ladders.findFirst({ where: eq(schema.ladders.id, demoId) });
    if (demo?.status !== "draft") throw new Error(`a ready ladder edited to fail should be a draft again, is ${demo?.status}`);
    if (!(await page.locator('[data-testid="publish-blocked"]').count())) throw new Error("failing edit shows no blockers");
    await page.fill('textarea[name="copy"]', cleanCopy);
    await submit(page, 'button:has-text("Save and re-check")');
    await submit(page, 'button:has-text("Mark ready")');
    demo = await db.query.ladders.findFirst({ where: eq(schema.ladders.id, demoId) });
    if (demo?.status !== "ready") throw new Error(`fixed ladder should be ready, is ${demo?.status}`);
    console.log("✓ a failing edit demotes ready to draft; fixed, it is ready again");

    // Live hour: post rung 1, rung 2; status goes live; reset returns to ready
    await submit(page, '[data-testid="rung-1"] button:has-text("Posted")');
    await expectText(page, "1/11 posted", "first rung posted");
    await expectText(page, "live", "status live");
    await submit(page, '[data-testid="rung-2"] button:has-text("Posted")');
    await expectText(page, "2/11 posted", "second rung posted");
    // While a live ladder fails: Undo works, posting another rung is refused, Reset lands on draft, not ready
    await page.fill('textarea[name="copy"]', `${cleanCopy}\nThe skinny version is in the comments?`);
    await submit(page, 'button:has-text("Save and re-check")');
    const rungButtons = page.locator('[data-testid="mark-rung"]');
    await submit(page, '[data-testid="mark-rung"] >> nth=1');
    await expectText(page, "1/11 posted", "undo allowed while blocked");
    await rungButtons.nth(2).evaluate((el) => el.removeAttribute("disabled"));
    await Promise.all([page.waitForResponse((r) => r.request().method() === "POST"), rungButtons.nth(2).click()]);
    await page.waitForURL(/blocked=/, { timeout: 10000 });
    demo = await db.query.ladders.findFirst({ where: eq(schema.ladders.id, demoId) });
    if (demo?.rungs.filter((r) => r.postedAt).length !== 1) throw new Error("posting a rung of a failing live ladder was not refused");
    await submit(page, 'button:has-text("Reset")');
    demo = await db.query.ladders.findFirst({ where: eq(schema.ladders.id, demoId) });
    if (demo?.status !== "draft" || demo.rungs.some((r) => r.postedAt)) throw new Error(`Reset on a failing ladder should land on draft with no rungs posted, got ${demo?.status}`);
    await page.fill('textarea[name="copy"]', cleanCopy);
    await submit(page, 'button:has-text("Save and re-check")');
    await submit(page, 'button:has-text("Mark ready")');
    console.log("✓ while blocked: undo allowed, posting refused, Reset lands on draft; fixed and ready again");
    await page.screenshot({ path: "screenshots/ld02-live-hour.png", fullPage: true });
    await submit(page, 'button:has-text("Reset")');
    await expectText(page, "0/11 posted", "reset");
    console.log("✓ live posting hour ticks rungs and resets");

    // Airtable copy escapes the numbering
    await page.click('button:has-text("Copy for Airtable")');
    const clip = await page.evaluate(() => navigator.clipboard.readText());
    if (!clip.startsWith("1\\. Mistake one.") || !clip.includes("\n---\n2\\. ")) throw new Error(`Airtable copy not escaped: ${clip.slice(0, 40)}`);
    console.log("✓ Airtable copy escapes rung numbers");

    // Composer hand-off
    const ladderUrl = page.url();
    await submit(page, 'button:has-text("Send to composer")');
    await page.waitForURL(/\/content\/[a-z0-9-]+\/compose/i);
    await expectText(page, "I quit every diet by week three", "body in composer");
    await page.screenshot({ path: "screenshots/ld03-composer.png", fullPage: true });
    await page.goto(ladderUrl);
    await expectText(page, "Open in composer", "linked to the content item");
    console.log("✓ sent to the composer with the body, caption and Threads chain");

    // Ladders tab on the content board, and the list shows both
    await page.goto(`${base}/content`);
    await page.click('a:has-text("Ladders")');
    await page.waitForURL(/\/content\/ladders/);
    await expectText(page, "SKIN — Mistakes Ladder", "list shows demo");
    await expectText(page, "SKIN — Loss / Rebuild", "list shows new");
    await expectText(page, "Next good slot", "cadence");
    await page.screenshot({ path: "screenshots/ld04-list.png", fullPage: true });
    console.log("✓ list and cadence");
  } finally {
    await browser.close();
  }
  if (failures.length) throw new Error(`Server errors:\n${failures.join("\n")}`);
  console.log("Ladders smoke passed");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
